export const countryMapper = (countryCode: string) => {
  if (countryCode === "DEN") return "DK";
  if (countryCode === "CHN") return "CN";
  if (countryCode === "INA") return "ID";
  if (countryCode === "JPN") return "JP";
  if (countryCode === "THA") return "TH";
  if (countryCode === "SGP") return "SG";
  if (countryCode === "MAS") return "MY";
  if (countryCode === "TPE") return "TW";
  if (countryCode === "HKG") return "HK";
  if (countryCode === "FRA") return "FR";
  if (countryCode === "CAN") return "CA";
  if (countryCode === "IRL") return "IE";
  if (countryCode === "GUA") return "GT";
  if (countryCode === "ISR") return "IL";
  if (countryCode === "KOR") return "KR";
  if (countryCode === "ESP") return "ES";
  if (countryCode === "VIE") return "VN";
  if (countryCode === "USA") return "US";
  if (countryCode === "IND") return "IN";
};
